#!/usr/bin/env sh

export INPUT_REPOSITORY_OWNER="mondeja"
export INPUT_REPOSITORY_NAME="pr-linked-issues-action-testing"

checkDependencies() {
  if [ -z "$(command -v "shunit2")" ]; then
    printf "You need to install shunit2 or add it to PATH to run tests.\n" >&2
    exit 1
  fi
}

checkEnvironmentVariables() {
  if [ -z "$GITHUB_TOKEN" ]; then
    printf "You need to define the environment variable GITHUB_TOKEN to run tests.\n" >&2
    exit 1
  fi
}

testNoLinkedPRs() {
  assertEquals "::set-output name=issues::" "$(INPUT_PULL_REQUEST=5 ./entrypoint)"
}

testLinkedPR() {
  assertEquals "::set-output name=issues::1" "$(INPUT_PULL_REQUEST=4 ./entrypoint)"
}

testLinkedPRs() {
  assertEquals "::set-output name=issues::1,2" "$(INPUT_PULL_REQUEST=3 ./entrypoint)"
}

testLinkedPRsOwners() {
  assertEquals \
    "::set-output name=issues::1,2,7
::set-output name=opener::7
::set-output name=others::1,2" \
    "$(INPUT_PULL_REQUEST=6 INPUT_OWNERS=true ./entrypoint)"
}

testLinkedPRsOwnersNoOthers() {
  assertEquals \
    "::set-output name=issues::1,2
::set-output name=opener::1,2
::set-output name=others::" \
    "$(INPUT_PULL_REQUEST=3 INPUT_OWNERS=true ./entrypoint)"
}

testLinkedPRsByContent() {
  assertEquals \
    "::set-output name=issues::0,2,7,34,55,57,58,59,60,65,77" \
    "$(INPUT_PULL_REQUEST=8 INPUT_ADD_LINKS_BY_CONTENT="
**Closes**: #{issue_number}
fishes #{issue_number}
humancipates #{issue_number}
makes #{issue_number} crazy
resolves #{issue_number} even if not exists
[{issue_number}]
...{issue_number}..
\${issue_number}^
({issue_number})
#
# Lines starting with '#' character must be ignored
#
{{issue_number}}
|{issue_number}|" ./entrypoint)"
}

testLinkedPrsByContentOwners() {
  assertEquals \
    "::set-output name=issues::2,7,34
::set-output name=opener::7
::set-output name=others::2
::set-output name=null::34" \
    "$(INPUT_OWNERS=true INPUT_PULL_REQUEST=8 INPUT_ADD_LINKS_BY_CONTENT="
**Closes**: #{issue_number}
fishes #{issue_number}" ./entrypoint)"
}

testLinkPrsByContentDontContainPlaceholder() {
  assertEquals \
    "The line 'foo' of the input 'add_links_by_content' does not contains the '{issue_number}' placeholder." \
    "$(INPUT_PULL_REQUEST=8 INPUT_ADD_LINKS_BY_CONTENT="foo" ./entrypoint 2>&1)"
}

main() {
  checkDependencies
  checkEnvironmentVariables
  . shunit2
}

main
